import { ContentModel } from '../models/Content.model.js';
import { logger } from '../utils/logger.js';

export const SEED_CONTENT_ITEMS = [
  // ==================== 1. WORDS & IDIOMS ====================
  {
    type: 'WORD',
    category: 'Words',
    difficulty: 'Medium',
    title: 'Perseverance',
    meaning: 'Persistence in doing something despite difficulty or delay in achieving success.',
    contentOverview: 'Refers to sustained effort, endurance, and mental toughness through challenges.',
    hint: 'Share a story of a personal or professional project where perseverance yielded long-term success.',
    suggestedDurationSeconds: 90,
  },
  {
    type: 'WORD',
    category: 'Words',
    difficulty: 'Easy',
    title: 'Serendipity',
    meaning: 'The occurrence and development of events by chance in a happy or beneficial way.',
    contentOverview: 'Derived from the Persian tale of Serendip, referring to unexpected discoveries made while seeking something else.',
    hint: 'Tell a story about a happy accident in technology or personal growth that opened unexpected opportunities.',
    suggestedDurationSeconds: 90,
  },
  {
    type: 'WORD',
    category: 'Words',
    difficulty: 'Hard',
    title: 'Equanimity',
    meaning: 'Mental calmness, composure, and evenness of temper, especially in a difficult situation.',
    contentOverview: 'Rooted in Stoic philosophy, equanimity represents maintaining steady leadership during high-stakes crisis.',
    hint: 'Contrast panic with calm, measured decision-making during executive moments.',
    suggestedDurationSeconds: 120,
  },
  {
    type: 'WORD',
    category: 'Words',
    difficulty: 'Hard',
    title: 'Perspicacity',
    meaning: 'The quality of having a ready insight into things; shrewdness and acute mental discernment.',
    contentOverview: 'High perspicacity allows leaders to anticipate market disruptions before competitors notice signals.',
    hint: 'Detail how keen observation and active listening build strategic foresight.',
    suggestedDurationSeconds: 120,
  },
  {
    type: 'WORD',
    category: 'Words',
    difficulty: 'Medium',
    title: 'Magnanimous',
    meaning: 'Generous or forgiving, especially toward a rival or less powerful person.',
    contentOverview: 'Latin origin meaning "great-souled". Demonstrates humble strength and high emotional intelligence.',
    hint: 'Explain why gracious leadership earns enduring loyalty from teams and partners.',
    suggestedDurationSeconds: 120,
  },
  {
    type: 'WORD',
    category: 'Words',
    difficulty: 'Easy',
    title: 'Eloquence',
    meaning: 'Fluent or persuasive speaking or writing.',
    contentOverview: 'The art of expressing ideas powerfully to inspire, move, or persuade an audience.',
    hint: 'Explain how mastering vocal cadence and clarity transforms career trajectories.',
    suggestedDurationSeconds: 90,
  },
  {
    type: 'WORD',
    category: 'Words',
    difficulty: 'Easy',
    title: 'Resilience',
    meaning: 'The capacity to recover quickly from difficulties; toughness.',
    contentOverview: 'The psychological ability to bounce back from setbacks, failures, or intense pressure.',
    hint: 'Detail how overcoming failure builds unshakeable confidence in senior leadership.',
    suggestedDurationSeconds: 90,
  },
  {
    type: 'WORD',
    category: 'Words',
    difficulty: 'Medium',
    title: 'Alacrity',
    meaning: 'Brisk and cheerful readiness to take action.',
    contentOverview: 'Demonstrating enthusiasm, speed, and positive energy when responding to new challenges.',
    hint: 'Highlight how responding to unexpected opportunities with alacrity creates team momentum.',
    suggestedDurationSeconds: 90,
  },
  {
    type: 'WORD',
    category: 'Words',
    difficulty: 'Medium',
    title: 'Ubiquitous',
    meaning: 'Present, appearing, or found everywhere simultaneously.',
    contentOverview: 'Describes technologies like smartphones and cloud computing that permeate modern daily life.',
    hint: 'Analyze a product that transitioned from a niche luxury to a ubiquitous daily utility.',
    suggestedDurationSeconds: 120,
  },
  {
    type: 'WORD',
    category: 'Words',
    difficulty: 'Hard',
    title: 'Ineffable',
    meaning: 'Too great or extreme to be expressed or described in words.',
    contentOverview: 'Used to describe profound emotional states, artistic beauty, or transformative life achievements.',
    hint: 'Describe a moment in your journey that transcended verbal description.',
    suggestedDurationSeconds: 120,
  },
  {
    type: 'WORD',
    category: 'Words',
    difficulty: 'Hard',
    title: 'Obfuscate',
    meaning: 'To render unclear, confusing, or difficult to understand.',
    contentOverview: 'Often seen when technical jargon or complex legal language obscures basic truths.',
    hint: 'Contrast confusing jargon with clear, direct executive storytelling.',
    suggestedDurationSeconds: 120,
  },
  {
    type: 'WORD',
    category: 'Idioms',
    difficulty: 'Easy',
    title: 'Bite the Bullet',
    meaning: 'To face a difficult situation with courage and get it over with, despite reluctance.',
    contentOverview: 'Originates from battlefield surgeries prior to anesthesia. It represents making decisive choices under pressure.',
    hint: 'Share a story about tackling a tough task procrastination only made worse.',
    suggestedDurationSeconds: 120,
  },
  {
    type: 'WORD',
    category: 'Idioms',
    difficulty: 'Easy',
    title: 'Burn the Midnight Oil',
    meaning: 'To work late into the night with extreme dedication and intense focus.',
    contentOverview: 'Refers to historical oil lamps used prior to electric light. Connects grit to long-term ambition.',
    hint: 'Contrast short-term hard work sprints with sustainable long-term pacing.',
    suggestedDurationSeconds: 120,
  },
  {
    type: 'WORD',
    category: 'Idioms',
    difficulty: 'Medium',
    title: 'Steal Someone’s Thunder',
    meaning: 'To take credit for someone else’s ideas or overshadow their accomplishment prematurely.',
    contentOverview: 'Originates from 18th-century playwright John Dennis. Highlighting recognition integrity in teams.',
    hint: 'Discuss workplace recognition integrity and giving team members credit.',
    suggestedDurationSeconds: 120,
  },
  {
    type: 'WORD',
    category: 'Idioms',
    difficulty: 'Easy',
    title: 'Hit the Nail on the Head',
    meaning: 'To describe exactly what is causing a situation or problem with total precision.',
    contentOverview: 'Carpentry precision applied to executive decision-making and root cause analysis.',
    hint: 'Explain how clear root-cause analysis eliminates workplace ambiguity.',
    suggestedDurationSeconds: 120,
  },

  // ==================== 2. TOPICS ====================
  {
    type: 'TOPIC',
    category: 'General',
    difficulty: 'Easy',
    title: 'The Impact of Social Media on Modern Youth Relationships',
    meaning: 'Exploring how instant messaging and digital platforms shape human empathy and communication habits.',
    contentOverview: 'Social media platforms connect billions daily but can also create superficial validation loops. Consider balancing digital convenience with real-life presence.',
    hint: 'Structure your talk with 1 personal observation, 1 pros/cons breakdown, and 1 recommendation for digital balance.',
    suggestedDurationSeconds: 120,
  },
  {
    type: 'TOPIC',
    category: 'General',
    difficulty: 'Medium',
    title: 'Why Continuous Lifelong Learning is Necessary in the 21st Century',
    meaning: 'The necessity of constantly updating skills to adapt to rapidly evolving technologies and career landscapes.',
    contentOverview: 'Static education models are giving way to lifelong micro-learning. Workers who adapt continuously build stronger career resilience.',
    hint: 'Emphasize adaptability and give an example of a skill that became obsolete over the past decade.',
    suggestedDurationSeconds: 150,
  },
  {
    type: 'TOPIC',
    category: 'Technology & AI',
    difficulty: 'Hard',
    title: 'Ethical Dilemmas of Autonomous AI Robotics and AGI Deployment',
    meaning: 'Evaluating moral accountability, data privacy, and societal safety as AI systems approach human cognitive levels.',
    contentOverview: 'AGI brings potential cures and automation but raises existential questions regarding alignment, job displacement, and military automation.',
    hint: 'Use the PREP framework (Point, Reason, Example, Point) to deliver a balanced argument on safety regulations.',
    suggestedDurationSeconds: 180,
  },
  {
    type: 'TOPIC',
    category: 'Business & Entrepreneurship',
    difficulty: 'Medium',
    title: 'Series A Venture Pitch: Defending ARR Growth & Customer Retention',
    meaning: 'Presenting high-impact financial metrics and competitive moats to tier-1 venture capitalists.',
    contentOverview: 'Investors evaluate monthly ARR growth rates, CAC payback periods, net revenue retention (NRR), and market size scalability.',
    hint: 'Open with explosive traction metrics, explain unit economics, and state your capital ask clearly.',
    suggestedDurationSeconds: 150,
  },
  {
    type: 'TOPIC',
    category: 'Sports',
    difficulty: 'Easy',
    title: 'How Sports Build Grit, Discipline, and Executive Leadership',
    meaning: 'Connecting athletic training principles—perseverance under loss and teamwork—to professional leadership.',
    contentOverview: 'Athletes learn resilience by failing publicly and adjusting strategy. These mental models translate directly to executive decision-making.',
    hint: 'Share a story of a legendary sports comeback and draw 2 key takeaways for corporate teams.',
    suggestedDurationSeconds: 120,
  },
  {
    type: 'TOPIC',
    category: 'Education',
    difficulty: 'Medium',
    title: 'Replacing Standardized Examinations in Favor of Real-World Project Portfolios',
    meaning: 'Assessing student capabilities through real-world creative output rather than memorization tests.',
    contentOverview: 'Rote memorization tests often fail to measure critical thinking, collaboration, or problem-solving skills needed in modern workplaces.',
    hint: 'Highlight how portfolio-based learning models mirror actual career deliverables.',
    suggestedDurationSeconds: 150,
  },

  // ==================== 3. QUESTIONS ====================
  {
    type: 'QUESTION',
    category: 'Interview',
    difficulty: 'Easy',
    title: 'Tell me about a time you led a team through an unexpected operational crisis.',
    meaning: 'Evaluating behavioral leadership resilience, delegation, and composure under pressure.',
    contentOverview: 'Interviewers look for emotional intelligence, clear delegation, and measurable recovery metrics.',
    hint: 'Use the STAR framework (Situation 20%, Task 10%, Action 50%, Result 20%) to structure your response.',
    suggestedDurationSeconds: 120,
  },
  {
    type: 'QUESTION',
    category: 'Interview',
    difficulty: 'Medium',
    title: 'How do you prioritize technical debt versus feature shipping under aggressive deadlines?',
    meaning: 'Testing engineering judgment, pragmatic trade-offs, and architecture stewardship.',
    contentOverview: 'Leaders must balance immediate revenue opportunities with systemic code maintenance.',
    hint: 'Explain your priority matrix balancing customer impact against long-term stability.',
    suggestedDurationSeconds: 150,
  },
  {
    type: 'QUESTION',
    category: 'General',
    difficulty: 'Easy',
    title: 'What single decision in your life taught you the most profound character lesson?',
    meaning: 'Reflecting on personal choices, unexpected outcomes, and self-awareness.',
    contentOverview: 'Authentic storytelling builds deep trust with interviewers when speakers share vulnerability.',
    hint: 'Set the scene, explain the core dilemma, describe your choice, and highlight key growth.',
    suggestedDurationSeconds: 120,
  },

  // ==================== 4. CORPORATE TALKS ====================
  {
    type: 'CORPORATE_TALK',
    category: 'Executive Pitch',
    difficulty: 'Medium',
    title: 'Series A Venture Pitch: Defending ARR Trajectory & Unit Economics',
    meaning: 'Presenting high-impact financial traction and competitive moats to tier-1 venture capitalists.',
    contentOverview: 'Investors evaluate monthly ARR growth rates, CAC payback periods, net revenue retention (NRR), and TAM scalability.',
    hint: 'Open with explosive traction metrics, explain unit economics, and state your capital ask clearly.',
    suggestedDurationSeconds: 150,
  },
  {
    type: 'CORPORATE_TALK',
    category: 'Townhall Address',
    difficulty: 'Medium',
    title: 'Townhall Address: Navigating Strategic Company Reorganization & Remote Alignment',
    meaning: 'Delivering empathetic, transparent guidance during organizational shifts.',
    contentOverview: 'During restructuring, employees require honest communication, strategic clarity, and long-term vision.',
    hint: 'Balance empathetic transparency with unshakeable confidence in the company strategic roadmap.',
    suggestedDurationSeconds: 150,
  },
  {
    type: 'CORPORATE_TALK',
    category: 'Product Launch',
    difficulty: 'Hard',
    title: 'Keynote Product Launch: Announcing Next-Gen Enterprise AI Automation',
    meaning: 'Unveiling a flagship software platform to enterprise customers, press, and industry analysts.',
    contentOverview: 'Product keynotes combine problem framing, dramatic live feature reveals, testimonial quotes, and pricing clarity.',
    hint: 'Use the classic Jobsian framework: 1. State industry pain point, 2. Reveal breakthrough feature, 3. Show live demo impact.',
    suggestedDurationSeconds: 180,
  },
  {
    type: 'CORPORATE_TALK',
    category: 'Crisis Management',
    difficulty: 'Hard',
    title: 'PR Crisis Response: SLA Outage Containment & Enterprise Remediation',
    meaning: 'Managing executive communications during critical infrastructure downtime.',
    contentOverview: 'Enterprise clients demand immediate root-cause transparency, containment timelines, and SLA compensation.',
    hint: 'Take direct accountability, state containment steps, and detail permanent remediation engineering.',
    suggestedDurationSeconds: 180,
  },
];

export async function seedContentDatabase(): Promise<void> {
  try {
    const existingCount = await ContentModel.countDocuments();
    if (existingCount === 0) {
      logger.info('Populating MongoDB Content Collection with initial dataset...');
      await ContentModel.insertMany(SEED_CONTENT_ITEMS);
      logger.info(`Successfully seeded ${SEED_CONTENT_ITEMS.length} content items into MongoDB database!`);
    } else {
      logger.info(`MongoDB Content Collection already contains ${existingCount} documents.`);
    }
  } catch (err) {
    logger.warn('Content DB Seeding Error:', err);
  }
}
